name: notification_hub
description: "An event broadcasting mechanism designed for dispatching notifications to registered observers, inspired by the structure of the iOS Notification Center."
version: 1.0.3
homepage: https://github.com/Abdullah8888/notification_hub

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  provider: ^6.1.2

flutter: